import Logo from "../../Components/Branding/Logo";

export default function LegalPage() {
  return (
    <div className="min-h-screen bg-[#070B14] text-slate-100 font-sans pb-20">
      {/* Header */}
      <header className="border-b border-slate-800/80 bg-[#070B14]/80 backdrop-blur-md sticky top-0 z-50 px-6 py-4">
        <div className="max-w-7xl mx-auto flex justify-between items-center">
          <Logo />
          <a
            href="/"
            className="bg-slate-800 hover:bg-slate-700 text-slate-300 text-xs font-bold px-4 py-2.5 rounded-xl transition"
          >
            ← Back to Main Site
          </a>
        </div>
      </header>

      <main className="max-w-4xl mx-auto px-6 pt-12 space-y-10">
        <div>
          <span className="text-xs font-bold uppercase tracking-widest text-emerald-400">
            Regulatory Compliance & Platform Policies
          </span>
          <h1 className="text-3xl md:text-5xl font-black text-white mt-1">
            Terms of Service & Privacy Policy
          </h1>
          <p className="text-slate-400 text-sm mt-2">
            InvestNorth Canada Pan-Canadian Economic Portal
          </p>
        </div>

        <div className="bg-slate-900/90 border border-slate-800 rounded-3xl p-8 md:p-12 space-y-8 shadow-2xl">
          <section className="space-y-3">
            <h2 className="text-xl font-bold text-white border-b border-slate-800 pb-2">
              1. Non-Legal Advisory & Regulatory Scope
            </h2>
            <p className="text-slate-300 text-xs leading-relaxed">
              InvestNorth Canada operates exclusively as a business strategy, corporate consulting, acquisition matching, and economic research platform. InvestNorth Canada is <strong>not a law firm</strong> and is <strong>not a Regulated Canadian Immigration Consultant (RCIC)</strong>.
            </p>
            <p className="text-slate-400 text-xs leading-relaxed">
              No attorney-client privilege or regulated legal representation is formed by accessing this portal. All legal filings, visa applications, and official Provincial Nominee Program (PNP) submissions are managed independently by licensed Canadian immigration attorneys or certified RCIC legal partners upon formal referral.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-bold text-white border-b border-slate-800 pb-2">
              2. Platform Terms of Use
            </h2>
            <p className="text-slate-300 text-xs leading-relaxed">
              By utilizing the InvestNorth Canada website and evaluation tools, applicants agree to provide accurate financial, managerial, and operational background information. Preliminary compatibility metrics generated by our Intake Wizard serve as analytical estimations based on provincial guidelines and do not guarantee final approval by provincial immigration authorities or Immigration, Refugees and Citizenship Canada (IRCC).
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-bold text-white border-b border-slate-800 pb-2">
              3. Privacy & Data Protection Policy
            </h2>
            <p className="text-slate-300 text-xs leading-relaxed">
              We maintain strict confidentiality over all client financial records, personal identification, net worth calculations, and business intentions.
            </p>
            <p className="text-slate-400 text-xs leading-relaxed">
              Applicant information submitted through our intake forms is encrypted and only transmitted to municipal economic development officers or partner law firms following express written authorization and engagement agreement execution. We do not sell or rent user data to third-party brokers.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-bold text-white border-b border-slate-800 pb-2">
              4. Advisory Retainers & Deliverables
            </h2>
            <p className="text-slate-300 text-xs leading-relaxed">
              Retainer payments processed via our integrated billing system compensate InvestNorth Canada for bespoke market analysis, 3D site inspections, municipal alignment briefs, and certified commercial business plan formulation.
            </p>
          </section>
        </div>

        <div className="text-center">
          <a
            href="/#wizard"
            className="inline-block bg-emerald-500 hover:bg-emerald-400 text-slate-950 font-bold px-8 py-3.5 rounded-xl transition shadow-xl text-xs"
          >
            Return to Investor Audit Wizard →
          </a>
        </div>
      </main>
    </div>
  );
}